document.writeln("        <div class=\'w3-container w3-light-grey\'>");
document.writeln("            <img src=\'./image/gt-logo.svg\' alt=\'gt-logo\' style=\'width:20%\'>");
document.writeln("            <img style=\'width:5%\'>");
document.writeln("            <img src=\'./image/Clemson-logo.svg\' alt=\'Clemson-logo\' style=\'width:20%\'>");
document.writeln("            <img style=\'width:5%\'>");
document.writeln("            <img src=\'./image/UAB-logo.png\' alt=\'UAB-logo\' style=\'width:40%\'>");
document.writeln("            <img style=\'width:5%\'>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'w3-container w3-amber\'>");
document.writeln("            <img style=\'width:9%\'>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'w3-container w3-amber\'>");
document.writeln("            <img style=\'width:9%\'>");
document.writeln("            <img src=\'./image/title-font6.png\' alt=\'Joint SIAM Student Conference\' style=\'width:80%\'>");
document.writeln("            <img style=\'width:9%\'>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'w3-container w3-amber\'>");
document.writeln("            <img style=\'width:9%\'>");
document.writeln("        </div>");
document.writeln("");
// document.writeln("        <div class=\'w3-bar w3-2020-navy-blazer\'>");
// document.writeln("            <a href=\'./i\' class=\'w3-bar-item w3-button w3-black w3-mobile\' style=\'width: 14.28%\'>Home Page</a>");
// document.writeln("            <a href=\'#\' class=\'w3-bar-item w3-button w3-mobile w3-border-right\' style=\'width: 14.28%\'>Schedule</a>");
// document.writeln("            <a href=\'#\' class=\'w3-bar-item w3-button w3-mobile w3-border-right\' style=\'width: 14.28%\'>Abstracts</a>");
// document.writeln("            <a href=\'#\' class=\'w3-bar-item w3-button w3-mobile w3-border-right\' style=\'width: 14.28%\'>Participants</a>");
// document.writeln("            <a href=\'#\' class=\'w3-bar-item w3-button w3-mobile w3-border-right\' style=\'width: 14.28%\'>Registration</a>");
// document.writeln("            <a href=\'#\' class=\'w3-bar-item w3-button w3-mobile w3-border-right\' style=\'width: 14.28%\'>Gallery</a>");
// document.writeln("            <a href=\'#\' class=\'w3-bar-item w3-button w3-mobile\' style=\'width: 14.28%\'>Contact Us</a>");
// document.writeln("        </div>");
